apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: distilbert-classifier
  labels:
    app: distilbert-classifier
spec:
  to:
    kind: Service
    name: distilbert-classifier
  port:
    targetPort: 8080
  tls:
    termination: passthrough
