apiVersion: v1
kind: Service
metadata:
  name: distilbert-classifier
  labels:
    app: distilbert-classifier
spec:
  selector:
    app: distilbert-classifier
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
